const products=[
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },

    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },

    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },
    {
        _id:'1',
        name:'Nike Air Max 97',
        image:'/images/nikeairmax',
        description:'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.',
        brand:'Nike',
        category:'Men',
        price:16995.00,
        countInStock:10,
        numReviews:12,
    },


]

export default products;